-- NASOI · demo accounts (generated by scripts/make-seed.ts)
-- Passwords are bcrypt hashes. Existing users are left untouched.
insert into users (id, role, name, mobile, email, password_hash) values
  ('DEO126', 'deo', 'Rahul Kumar', '9717323761', 'rahul.demo@example.com', '$2b$12$mItG5XGl8W6LU6jG/uVIduUXWi17uy77YOkypnyp3/aYptn8.j2km'),
  ('DEO127', 'deo', 'Priya Sharma', '9811100022', 'priya.demo@example.com', '$2b$12$WJC6/YrHWpw3FLsef7Fec./pDEyUhr4qBL5exMokQvv2Lu/8rdoNK'),
  ('VR101', 'verifier', 'Anjali Verma', '9990011223', 'verifier.demo@example.com', '$2b$12$27BbtRux9wVXpwdHp3vYDORqG50MPmFEOzQrf3vlSD5fjIBvqerI.'),
  ('ADMIN', 'admin', 'Super Admin', '9000000000', 'admin.demo@example.com', '$2b$12$g41qlT5pbNmAQXwuhUmFw.Ti8U3XPhI6tqHR8pktXH.rc9d6KmXF6')
on conflict (id) do nothing;
