// Generates db/seed/001_demo_users.sql with bcrypt hashes of the demo passwords.
// Demo accounts match the frontend demo data. Change / delete them before real launch.
import bcrypt from "bcryptjs";
import { mkdirSync, writeFileSync } from "node:fs";

const users = [
  { id: "DEO126", role: "deo", name: "Rahul Kumar", mobile: "9717323761", email: "rahul.demo@example.com", password: "Abcd@2026" },
  { id: "DEO127", role: "deo", name: "Priya Sharma", mobile: "9811100022", email: "priya.demo@example.com", password: "Abcd@2026" },
  { id: "VR101", role: "verifier", name: "Anjali Verma", mobile: "9990011223", email: "verifier.demo@example.com", password: "Abcd@2026" },
  { id: "ADMIN", role: "admin", name: "Super Admin", mobile: "9000000000", email: "admin.demo@example.com", password: "Admin@2026" },
];

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = users.map((u) => `  (${q(u.id)}, ${q(u.role)}, ${q(u.name)}, ${q(u.mobile)}, ${q(u.email)}, ${q(bcrypt.hashSync(u.password, 12))})`);

const sql = `-- NASOI · demo accounts (generated by scripts/make-seed.ts)
-- Passwords are bcrypt hashes. Existing users are left untouched.
insert into users (id, role, name, mobile, email, password_hash) values
${rows.join(",\n")}
on conflict (id) do nothing;
`;
mkdirSync("db/seed", { recursive: true });
writeFileSync("db/seed/001_demo_users.sql", sql);
console.log("Wrote db/seed/001_demo_users.sql");
